apiVersion: apps/v1
kind: Deployment
metadata:
  name: vscode-server
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: vscode-server
      app.kubernetes.io/name: code-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: vscode-server
        app.kubernetes.io/name: code-server
    spec:
      containers:
        - image: docker.io/linuxserver/code-server:4.93.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            tcpSocket:
              port: http
            timeoutSeconds: 10
          name: vscode-server
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
            - name: SUDO_PASSWORD
              value: "password"
            - name: DOCKER_MODS
              value: "linuxserver/mods:universal-package-install|linuxserver/mods:code-server-zsh|linuxserver/mods:universal-docker-in-docker|linuxserver/mods:code-server-extension-arguments"
            - name: VSCODE_EXTENSION_IDS
              value: "vscode-icons-team.vscode-icons|ms-toolsai.jupyter"
            - name: INSTALL_PACKAGES
              value: "git|iputils-ping|python3-ipykernel|python3-numpy|python3-venv|python3-matplotlib"
            - name: INSTALL_PIP_PACKAGES
              value: "" # not working
          ports:
            - containerPort: 8443
              name: http
              protocol: TCP
          volumeMounts:
            - name: workspace-volume
              mountPath: "/config/workspace"
      volumes:
        - name: workspace-volume
          persistentVolumeClaim:
            claimName: vscode-server-pvc
      dnsPolicy: ClusterFirst
      serviceAccountName: default
