apiVersion: apps/v1
kind: Deployment
metadata:
  name: vscode-server
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: vscode-server
      app.kubernetes.io/name: code-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: vscode-server
        app.kubernetes.io/name: code-server
    spec:
      containers:
        - image: docker.io/linuxserver/code-server:v4.0.2-ls111
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            tcpSocket:
              port: http
            timeoutSeconds: 10
          name: vscode-server
          env:
            - name: DOCKER_MODS
              value: "linuxserver/mods:universal-package-install|linuxserver/mods:code-server-zsh|linuxserver/mods:universal-docker-in-docker|linuxserver/mods:code-server-extension-arguments"
            - name: VSCODE_EXTENSION_IDS
              value: "vscode-icons-team.vscode-icons|ms-azuretools.vscode-docker"
            - name: INSTALL_PACKAGES
              value: "rsync|git|nginx"
            - name: INSTALL_PIP_PACKAGES
              value: "requests|numpy|conda"
          ports:
            - containerPort: 8443
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            tcpSocket:
              port: http
            timeoutSeconds: 10
          volumeMounts: null
      dnsPolicy: ClusterFirst
      serviceAccountName: default
