apiVersion: apps/v1
kind: Deployment
metadata:
  name: vscode-server
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: vscode-server
      app.kubernetes.io/name: code-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: vscode-server
        app.kubernetes.io/name: code-server
    spec:
      containers:
        - image: ghcr.io/linuxserver/code-server:version-v3.11.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            tcpSocket:
              port: http
            timeoutSeconds: 10
          name: vscode-server
          ports:
            - containerPort: 8443
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            tcpSocket:
              port: http
            timeoutSeconds: 10
          volumeMounts: null
      dnsPolicy: ClusterFirst
      serviceAccountName: default
