apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume
  namespace: applications
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vscode-server-pvc
  namespace: applications
spec:
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  
